### Params
### AI Search
@AI_SRCH_ENDPOINT=https://srch-searchi-eastus.search.windows.net
@AI_SRCH_API_VERSION=2024-05-01-preview 
@AI_SRCH_API_KEY=WRITE_KEY_HERE_AND_NEVER_COMMIT

### Cognitive Services
@COGNITIVE_MULTI_ACCOUNT_ENDPOINT=https://aisa-searchi-japaneast.cognitiveservices.azure.com/
@COGNITIVE_MULTI_ACCOUNT_API_KEY=WRITE_KEY_HERE_AND_NEVER_COMMIT
@COGNITIVE_MULTI_ACCOUNT_API_VERSION=2023-02-01-preview
@MODEL_VERSION=2023-04-15


### embed_images_index ------------------------------------------------------------------------
### Index ----------------------------------------
@EMBED_IMAGE_INDEX_NAME=embed-images-index

### List
GET {{AI_SRCH_ENDPOINT}}/indexes?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Delete
DELETE {{AI_SRCH_ENDPOINT}}/indexes/{{EMBED_IMAGE_INDEX_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Create
PUT {{AI_SRCH_ENDPOINT}}/indexes/{{EMBED_IMAGE_INDEX_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

< ./embed_image_index.json



### docs_index --------------------------------------------------------------------------------
### DataSource -----------------------------------
@DATASOURCE_NAME=docs-blob-datasource

### List
GET {{AI_SRCH_ENDPOINT}}/datasources?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Delete
DELETE {{AI_SRCH_ENDPOINT}}/datasources/{{DATASOURCE_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Create
PUT {{AI_SRCH_ENDPOINT}}/datasources/{{DATASOURCE_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

< ./datasource.json


### Index ----------------------------------------
@DOCS_INDEX_NAME=docs-index

### List
GET {{AI_SRCH_ENDPOINT}}/indexes?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Delete
DELETE {{AI_SRCH_ENDPOINT}}/indexes/{{DOCS_INDEX_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Create
PUT {{AI_SRCH_ENDPOINT}}/indexes/{{DOCS_INDEX_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

< ./docs_index.json


### Skill Set ------------------------------------
@SKILLSET_NAME=docs-skillset

### List
GET {{AI_SRCH_ENDPOINT}}/skillsets?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Delete
DELETE {{AI_SRCH_ENDPOINT}}/skillsets/{{SKILLSET_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Create
PUT {{AI_SRCH_ENDPOINT}}/skillsets/{{SKILLSET_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

< ./skillset.json


### Indexer --------------------------------------
@INDEXER_NAME=docs-indexer

### List
GET {{AI_SRCH_ENDPOINT}}/indexers?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Delete
DELETE {{AI_SRCH_ENDPOINT}}/indexers/{{INDEXER_NAME}}/?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Create
PUT {{AI_SRCH_ENDPOINT}}/indexers/{{INDEXER_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

< ./indexer.json

### Reset
POST {{AI_SRCH_ENDPOINT}}/indexers/{{INDEXER_NAME}}/reset?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Run
POST {{AI_SRCH_ENDPOINT}}/indexers/{{INDEXER_NAME}}/run?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Stautus
GET {{AI_SRCH_ENDPOINT}}/indexers/{{INDEXER_NAME}}/status?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}


### Search ------------------------------------------------------------------------------------
### Text ----------------------------------------
POST {{AI_SRCH_ENDPOINT}}/indexes/{{DOCS_INDEX_NAME}}/docs/search?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

{
    "search": "Gobi",
    "queryType": "full",
    "filter": "",
    "searchFields": "",
    "select": "metadata_storage_name",
    "count": true
}


### Vector --------------------------------------
### Embed image
# @name embed_image

POST {{COGNITIVE_MULTI_ACCOUNT_ENDPOINT}}/computervision/retrieval:vectorizeImage?api-version={{COGNITIVE_MULTI_ACCOUNT_API_VERSION}}&model-version={{MODEL_VERSION}}
Content-Type: application/octet-stream
Ocp-Apim-Subscription-Key: {{COGNITIVE_MULTI_ACCOUNT_API_KEY}}

< ./../images/normalized_images_11.jpg

### Save value
@vector_image={{embed_image.response.body.vector}}

### Search
@VECTOR_SEARCH_API_VERSION=2023-11-01

POST {{AI_SRCH_ENDPOINT}}/indexes/{{EMBED_IMAGE_INDEX_NAME}}/docs/search?api-version={{VECTOR_SEARCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

{
    "count": true,
    "select": "id,ParentKey",
    "vectorQueries": [
        {
            "kind": "vector",
            "vector": {{vector_image}},
            "fields": "image_vector",
            "k": 5
        }
    ]
}