### Params
### AI Search
@AI_SRCH_ENDPOINT=https://srch-searchi-eastus.search.windows.net
@AI_SRCH_API_VERSION=2024-05-01-preview
@AI_SRCH_API_KEY=WRITE_KEY_HERE_AND_NEVER_COMMIT

### Cognitive Services
@COGNITIVE_MULTI_ACCOUNT_ENDPOINT=https://aisa-searchi-japaneast.cognitiveservices.azure.com/
@COGNITIVE_MULTI_ACCOUNT_API_KEY=WRITE_KEY_HERE_AND_NEVER_COMMIT
@COGNITIVE_MULTI_ACCOUNT_API_VERSION=2023-02-01-preview
@MODEL_VERSION=2023-04-15


### docs_chunk --------------------------------------------------------------------------------
@DOCS_CHUNK_INDEX=docs-chunks

### Delete
DELETE {{AI_SRCH_ENDPOINT}}/indexes/{{DOCS_CHUNK_INDEX}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Create
PUT {{AI_SRCH_ENDPOINT}}/indexes/{{DOCS_CHUNK_INDEX}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

< ./docs_chunk_index.json


### docs_image --------------------------------------------------------------------------------
@DOCS_IMAGE_INDEX=docs-images

### Delete
DELETE {{AI_SRCH_ENDPOINT}}/indexes/{{DOCS_IMAGE_INDEX}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Create
PUT {{AI_SRCH_ENDPOINT}}/indexes/{{DOCS_IMAGE_INDEX}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

< ./docs_image_index.json


### docs_index --------------------------------------------------------------------------------
### DataSource -----------------------------------
@DATASOURCE_NAME=docs-blob-datasource

### Delete
DELETE {{AI_SRCH_ENDPOINT}}/datasources/{{DATASOURCE_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Create
PUT {{AI_SRCH_ENDPOINT}}/datasources/{{DATASOURCE_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

< ./datasource.json


### Index ----------------------------------------
@DOCS_INDEX_NAME=docs

### Delete
DELETE {{AI_SRCH_ENDPOINT}}/indexes/{{DOCS_INDEX_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Create
PUT {{AI_SRCH_ENDPOINT}}/indexes/{{DOCS_INDEX_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

< ./docs_index.json


### Skill Set ------------------------------------
@SKILLSET_NAME=docs-skillset

### Delete
DELETE {{AI_SRCH_ENDPOINT}}/skillsets/{{SKILLSET_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Create
PUT {{AI_SRCH_ENDPOINT}}/skillsets/{{SKILLSET_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

< ./docs-skillset.json


### Indexer --------------------------------------
@INDEXER_NAME=docs-indexer

### Delete
DELETE {{AI_SRCH_ENDPOINT}}/indexers/{{INDEXER_NAME}}/?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Create
PUT {{AI_SRCH_ENDPOINT}}/indexers/{{INDEXER_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

{
    "description": "",
    "dataSourceName": "{{DATASOURCE_NAME}}",
    "skillsetName": "{{SKILLSET_NAME}}",
    "targetIndexName": "{{DOCS_INDEX_NAME}}",
    "disabled": null,
    "schedule": {},
    "parameters": {
        "batchSize": null,
        "maxFailedItems": 10,
        "maxFailedItemsPerBatch": 5,
        "base64EncodeKeys": null,
        "configuration": {
            "dataToExtract": "contentAndMetadata",
            "parsingMode": "default",
            "imageAction": "generateNormalizedImages"
        }
    },
    "fieldMappings": [],
    "outputFieldMappings": [],
    "cache": null,
    "encryptionKey": null
}

### Reset
POST {{AI_SRCH_ENDPOINT}}/indexers/{{INDEXER_NAME}}/reset?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Run
POST {{AI_SRCH_ENDPOINT}}/indexers/{{INDEXER_NAME}}/run?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Status
GET {{AI_SRCH_ENDPOINT}}/indexers/{{INDEXER_NAME}}/status?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}


### Search ------------------------------------------------------------------------------------
### Text ----------------------------------------
POST {{AI_SRCH_ENDPOINT}}/indexes/{{DOCS_INDEX_NAME}}/docs/search?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

{
    "search": "Gobi",
    "queryType": "full",
    "filter": "",
    "searchFields": "",
    "select": "metadata_storage_name",
    "count": true
}


### Vector Search
@VECTOR_SEARCH_API_VERSION=2023-11-01

### Image
# @name embed_image

POST {{COGNITIVE_MULTI_ACCOUNT_ENDPOINT}}/computervision/retrieval:vectorizeImage?api-version={{COGNITIVE_MULTI_ACCOUNT_API_VERSION}}&model-version={{MODEL_VERSION}}
Content-Type: application/octet-stream
Ocp-Apim-Subscription-Key: {{COGNITIVE_MULTI_ACCOUNT_API_KEY}}

< ./../images/normalized_images_30.jpg

### Save value
@vector_image={{embed_image.response.body.vector}}

### Image Vector Search

POST {{AI_SRCH_ENDPOINT}}/indexes/{{DOCS_IMAGE_INDEX}}/docs/search?api-version={{VECTOR_SEARCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

{
    "count": true,
    "select": "id,URL",
    "vectorQueries": [
        {
            "kind": "vector",
            "vector": {{vector_image}},
            "fields": "image_vector",
            "k": 5
        }
    ]
}

### Text
# @name embed_text

POST {{COGNITIVE_MULTI_ACCOUNT_ENDPOINT}}/computervision/retrieval:vectorizeText?api-version={{COGNITIVE_MULTI_ACCOUNT_API_VERSION}}&model-version={{MODEL_VERSION}}
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{COGNITIVE_MULTI_ACCOUNT_API_KEY}}

{
    "text": "tell me about the Gobi desert."
}

### Save value
@vector_text={{embed_text.response.body.vector}}

### Text Vector Search
POST {{AI_SRCH_ENDPOINT}}/indexes/{{DOCS_CHUNK_INDEX}}/docs/search?api-version={{VECTOR_SEARCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

{
    "count": true,
    "select": "id,URL,chunk",
    "vectorQueries": [
        {
            "kind": "vector",
            "vector": {{vector_text}},
            "fields": "chunk_vector",
            "k": 5
        }
    ]
}