@AI_SRCH_ENDPOINT=https://srch-searchi-japaneast.search.windows.net
@AI_SRCH_API_VERSION=2024-05-01-preview 
@AI_SRCH_API_KEY=WRITE_KEY_HERE_AND_NEVER_COMMIT



### DataSource -----------------------------------
@DATASOURCE_NAME=docs-blob-datasource

### List
GET {{AI_SRCH_ENDPOINT}}/datasources?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}  

### Delete
DELETE {{AI_SRCH_ENDPOINT}}/datasources/{{DATASOURCE_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Create
PUT {{AI_SRCH_ENDPOINT}}/datasources/{{DATASOURCE_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

< ./definitions/datasource.json



### Skill Set -----------------------------------
@SKILLSET_NAME=docs-skillset
### List
GET {{AI_SRCH_ENDPOINT}}/skillsets?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}  

### Delete
DELETE {{AI_SRCH_ENDPOINT}}/skillsets/{{SKILLSET_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Create
PUT {{AI_SRCH_ENDPOINT}}/skillsets/{{SKILLSET_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

< ./definitions/skillset.json



### Index ---------------------------------------
@INDEX_NAME=docs-index

### List
GET {{AI_SRCH_ENDPOINT}}/indexes?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Delete
DELETE {{AI_SRCH_ENDPOINT}}/indexes/{{INDEX_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Create
PUT {{AI_SRCH_ENDPOINT}}/indexes/{{INDEX_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

< ./definitions/index.json



### Indexer ------------------------------------
@INDEXER_NAME=docs-indexer
### List
GET {{AI_SRCH_ENDPOINT}}/indexers?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Delete
DELETE {{AI_SRCH_ENDPOINT}}/indexers('{{INDEXER_NAME}}')?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

### Create
PUT {{AI_SRCH_ENDPOINT}}/indexers/{{INDEXER_NAME}}?api-version={{AI_SRCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SRCH_API_KEY}}

< ./definitions/indexer.json
