### local
### HttpTrigger
POST http://localhost:7071/api/HttpTrigger

### GenerateEmbeddings
POST http://localhost:7071/api/GenerateEmbeddings
Content-Type: application/octet-stream

< ./sample_images/cat.jpeg

### Azure
@FUNCTION_KEY=WRITE_KEY_HERE_AND_NEVER_COMMIT
### HttpTrigger
POST https://func-searchi-japaneast.azurewebsites.net/api/httptrigger?code={{FUNCTION_KEY}}

### GenerateEmbeddings
POST https://func-searchi-japaneast.azurewebsites.net/api/generateembeddings?code={{FUNCTION_KEY}}
Content-Type: application/octet-stream

< ./sample_images/cat.jpeg